language: python
sudo: false
python:
    - "3.6"
install:
    - pip install -U pip wheel setuptools coveralls
    - pushd ~
    - git clone --depth 1 https://github.com/pretix/pretix.git
    - cd pretix/src
    - pip3 install -Ur requirements.txt -r requirements/dev.txt
    - python setup.py develop
    - make all compress
    - popd
script:
    - flake8 --ignore=E123,F403,F401,N802,C901,W503,E402 .
    - isort -c -rc .
    - python setup.py develop
    - make
    - coverage run -m py.test --reruns 5 tests && coveralls
cache:
    directories:
        - $HOME/.cache/pip
addons:
  apt:
      packages:
          - enchant
          - myspell-de-de
          - aspell-en
